### ISSUE TITLE
concurrent map writes crashed erisdb

### ISSUE THREAD

**Issue by dennismckinnon** [eris-ltd/eris-db#143]
```
T    Tx:CallTx{TxInput{EA58F6DE2C3837D6F63178832DDBF823563643EC,1,14,/30A1643A8AA0.../,<nil>} -> 4326c9446051cdead4a3e824e576aba1fea23935: 0bfefed400000000000000000000000090f173ed9e6730526e4c155f252ac50635743b2700000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000143734373936633635373232643638363936343635000000000000000000000000}
-  }#06B99BE1BFC08C969C517A81DBBB0DD08C842B6C
  Validation{
c    Precommits: Vote{544/00/2(Precommit) BA29D5F3E411#PartSet{T:3 E6C46477D776} /09789324C8EF.../}
W    Vote{544/00/2(Precommit) BA29D5F3E411#PartSet{T:3 E6C46477D776} /14862D6AAC76.../}
W    Vote{544/00/2(Precommit) BA29D5F3E411#PartSet{T:3 E6C46477D776} /A3D95007BEC9.../}
-  }#C1B824E1117BFDF5D29EF3372B1E9DB11842A1AA
E}#0B00A587DB3BF5E0617E2372F10E2A73A58931CD module=consensus
�INFO[06-15|02:44:15] Broadcast                                module=p2p channel=20 msg="[NewRoundStep H:546 R:0 S:RoundStepNewHeight LCR:0]"
INFO[06-15|02:44:15] Send                                     module=p2p channel=20 conn=MConn{192.168.1.15:49823} msg="[NewRoundStep H:546 R:0 S:RoundStepNewHeight LCR:0]"
#fatal error: concurrent map writes
/fatal error: concurrent map read and map write

goroutine 34679 [running]:
runtime.throw(0xc7c850, 0x15)
L	/usr/lib/go/src/runtime/panic.go:547 +0x90 fp=0xc820ebd000 sp=0xc820ebcfe8
8runtime.mapdelete(0x9ec9e0, 0xc820119b30, 0xc820ebd0b8)
N	/usr/lib/go/src/runtime/hashmap.go:559 +0x5a fp=0xc820ebd060 sp=0xc820ebd000
�github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/events.(*EventSwitch).RemoveListener(0xc820190900, 0xc820ec28a0, 0x28)
�	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/events/events.go:72 +0xd7 fp=0xc820ebd110 sp=0xc820ebd060
xgithub.com/eris-ltd/eris-db/erisdb/pipe.(*events).Unsubscribe(0xc820084060, 0xc820ec28a0, 0x28, 0xc82115ae01, 0x0, 0x0)
d	/go/src/github.com/eris-ltd/eris-db/erisdb/pipe/events.go:27 +0x44 fp=0xc820ebd130 sp=0xc820ebd110
�github.com/eris-ltd/eris-db/erisdb/pipe.(*transactor).TransactAndHold(0xc820de4040, 0xc8214272c0, 0x40, 0x40, 0xc820eee340, 0x14, 0x14, 0xc821282a50, 0xe4, 0xe4, ...)
j	/go/src/github.com/eris-ltd/eris-db/erisdb/pipe/transactor.go:206 +0x528 fp=0xc820ebd360 sp=0xc820ebd130
�github.com/eris-ltd/eris-db/erisdb.(*ErisDbMethods).TransactAndHold(0xc820dde340, 0xc82011be00, 0xbbb5e0, 0xc8201046e0, 0x0, 0x0, 0xc8211854a8, 0x0, 0x0)
b	/go/src/github.com/eris-ltd/eris-db/erisdb/methods.go:420 +0x21d fp=0xc820ebd438 sp=0xc820ebd360
�github.com/eris-ltd/eris-db/erisdb.(*ErisDbMethods).TransactAndHold-fm(0xc82011be00, 0xbbb5e0, 0xc8201046e0, 0x0, 0x0, 0x411d01, 0x0, 0x0)
a	/go/src/github.com/eris-ltd/eris-db/erisdb/methods.go:103 +0x64 fp=0xc820ebd488 sp=0xc820ebd438
zgithub.com/eris-ltd/eris-db/erisdb.(*ErisDbJsonService).Process(0xc820de6150, 0xc821699340, 0x7f4d9ca11bf8, 0xc8201046e0)
f	/go/src/github.com/eris-ltd/eris-db/erisdb/json_service.go:94 +0x32a fp=0xc820ebd570 sp=0xc820ebd488
[github.com/eris-ltd/eris-db/erisdb.(*JsonRpcServer).handleFunc(0xc820dde360, 0xc8201046e0)
e	/go/src/github.com/eris-ltd/eris-db/erisdb/json_service.go:45 +0xa3 fp=0xc820ebd5c8 sp=0xc820ebd570
ugithub.com/eris-ltd/eris-db/erisdb.(*JsonRpcServer).(github.com/eris-ltd/eris-db/erisdb.handleFunc)-fm(0xc8201046e0)
```

**Comment by ebuchman** [comment]
fascinating. version? reproducible? contract do anything fancy?

**Comment by ebuchman** [comment]
well this is obviously the culprit, and wrong: https://github.com/eris-ltd/eris-db/blob/develop/Godeps/_workspace/src/github.com/tendermint/tendermint/events/events.go#L70

that should not be an RLock, but a normal Lock. serious bug!

**Comment by dennismckinnon** [comment]
Thanks E, Sorry for crap issue but came across just as I was about ready to head home and didn't want to lose the log.

The version was whatever version eris-cli is running with on develop branch. it is repeatable it seems to occur when I am sending a lot of transactions in quick successions. however I have not isolated this behaviour to be nicely reproducible. The network configuration is a three validator chain running elsewhere and I'm connected to and sending transactions through a non-validator node.

**Comment by benjaminbollen** [comment]
I started writing unit tests for tendermint/go-events and work towards reproducing the bug in the tests; then applying the fix as proposed
