### ISSUE TITLE
Fix deseriliastion of eris-mint events (thus fixing TestHTTPNameReg and other tests)

### ISSUE THREAD

**Issue by silasdavis** [eris-ltd/eris-db#201]
Here we are seeing a panic that is halting the test process. Appears to be a go-wire serialisation issue, where an unexpected type is being deserialised for an interface.

Looks like a bug in the re-implemented Subscribe function:

```
=== RUN   TestHTTPNameReg
INFO[08-12|15:47:09] Starting WSClient                        module=rpcclient impl="0.0.0.0:36657, /websocket"
Subscribing to event                    event=NameReg/ye_old_domain_name_HTTP
                                   listenerId=127.0.0.1:46404
Commit block                      blockheight=2
Reset checkCache                          txs=1
AppendTxtxNameTx{TxInput{E9B5D87313356465FAE33C406CE2C2979DE60BCB,1096,6,/94032325D883.../,PubKeyEd25519{583779C3BFA3F6C7E23C7D830A9C3D023A216B55079AD38BFED1207B94A19548}} -> ye_old_domain_name_HTTP: if not now, when}
Commit block                      blockheight=3
Reset checkCache                          txs=1
panic: Paniced on a Sanity Check: Unexpected struct type txs.EventDataTx for registered interface TMEventData. Was it registered as a pointer receiver rather than as a value receiver?

goroutine 71 [running]:
panic(0xbabe00, 0xc82047f890)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-common.PanicSanity(0xceb520, 0xc82047f840)
	/home/silas/code/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-common/errors.go:26 +0xf5
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-wire.JSONBytes(0xb6ae60, 0xc82047f750, 0x0, 0x0, 0x0)
	/home/silas/code/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-wire/util.go:33 +0x113
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-rpc/types.NewRPCResponse(0xe57108, 0x6, 0xb6ae60, 0xc82047f750, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/silas/code/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-rpc/types/types.go:55 +0x90
github.com/eris-ltd/eris-db/rpc/tendermint/core.(*TendermintRoutes).Subscribe.func1(0xb6b0a0, 0xc820298bc0)
	/home/silas/code/go/src/github.com/eris-ltd/eris-db/rpc/tendermint/core/routes.go:62 +0xf8
```

**Comment by silasdavis** [comment]
We define some event types in our package `txs`. But we deserialise them into `TMEventData` in subscribe which is owned by tendermint. Probably need to take control of that interface, or else use tendermint's events. See `EventDataTx` for example defined:

https://github.com/eris-ltd/eris-db/blob/develop/txs/events.go#L74

and here:
https://github.com/tendermint/tendermint/blob/64f773c88644650f0ca550ee744ad9adada5e994/types/events.go#L74

**Comment by benjaminbollen** [comment]
Yes, this is a bug in the TMSP refactor;  this has been copied and should be fully owned from `txs.events`

**Comment by benjaminbollen** [comment]
Possibly, for TMSP (which has the log field), we may look to add the log field to the txs.events type?
