### ISSUE TITLE
Chain stops making blocks

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-db#457]
@somak12 commented on [Wed Dec 14 2016](https://github.com/eris-ltd/eris-cli/issues/1138)

- [1.12.3, ] `docker version`
- [0.12.0 ] `eris version`
- [0.8.2 ] `docker-machine version`
- [linux ] operating system details 

I don't know the specific point where it is failing but when I do lots of transactions in the chain like 50 transactions say at a time, after a point chain stops creating blocks. Logs in the validator machines are as follows: 

enterPropose: Error signing proposal     module=consensus height=82511 round=0 error="Attempt of duplicate signing of proposal: Height 82511, Round 0"

EROR[12-14|05:56:05] Error with msg                           module=consensus type=*consensus.ProposalMessage peer=CF2A1540EC2ADBE520A904FFB8723BCFF9959D6909DC8CA79D4725D4CFC8714A error="Error invalid proposal signature" msg="[Proposal Proposal{82511/0 PartSet{T:1 26830F519835} -1 /5E97A61BFFB6.../}]"

WARN[12-14|05:56:11] Found conflicting vote from ourselves. Did you unsafe_reset a validator? module=consensus height=82511 round=0 type=2

Is there any specific reason for this behavior??  

---

@zramsay commented on [Wed Dec 14 2016](https://github.com/eris-ltd/eris-cli/issues/1138#issuecomment-267057185)

Hi @somak12 thanks for the bug report. We've seen similar behaviour pop up recently. Can you provide more details on how you created/started your chain? pinging @benjaminbollen for review of eris-db logs

---

@somak12 commented on [Thu Dec 15 2016](https://github.com/eris-ltd/eris-cli/issues/1138#issuecomment-267243164)

@zramsay I created chain with 1 root account + 4 participants + 3 validators. Im using docker machines(amazon driver) for the validators. As you can see things were working fine till height 82510. One thing is that after work I used to stop the chain and the eris service and restart it back when needed.    

---

@somak12 commented on [Thu Dec 15 2016](https://github.com/eris-ltd/eris-cli/issues/1138#issuecomment-267249588)

And Im uisng image = "quay.io/eris/db:0.12.1" for issue of chain not creating blocks due to use of curent timestamp in the contract..

---

@andytudhope commented on [Mon Jan 16 2017](https://github.com/eris-ltd/eris-cli/issues/1138#issuecomment-272775839)

I am having exactly the same issue. tried to leave a chain running over the weekend to test how big it would get and returned to find this message in the logs. Cleaning Eris and restarting the chains does nothing for me - still get `Found conflicting vote from ourselves. Did you unsafe_reset a validator?` in the logs.

[1.12.5 ] `docker version`
[0.12.0] `eris version`
[Mac El Capitan] `OS`

---

@marc4gov commented on [Mon Jan 16 2017](https://github.com/eris-ltd/eris-cli/issues/1138#issuecomment-272936772)

Look like I have something similar. I start 4 validators, that's ok. Then I start the root machine, looks like the chain is running (Height is increasing) but actually not making blocks. Logs shows messages like these:

```
INFO[01-16|14:37:12] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" peerRound=0 height=60 round=0 precommits=nil-BitArray index=0
INFO[01-16|14:37:12] Receive                                  module=consensus src="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" chId=20 msg="[HasVote VI:2 V:{60/00/2} VI:2]"
INFO[01-16|14:37:12] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" peerRound=0 height=60 round=0 precommits=nil-BitArray index=2
INFO[01-16|14:37:12] Receive                                  module=consensus src="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" chId=20 msg="[NewRoundStep H:60 R:0 S:RoundStepPrecommitWait LCR:0]"
INFO[01-16|14:37:12] Receive                                  module=consensus src="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" chId=20 msg="[HasVote VI:3 V:{60/00/2} VI:3]"
INFO[01-16|14:37:12] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" peerRound=0 height=60 round=0 precommits=nil-BitArray index=3
INFO[01-16|14:37:12] Receive                                  module=consensus src="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" chId=20 msg="[NewRoundStep H:60 R:0 S:RoundStepCommit LCR:0]"
INFO[01-16|14:37:12] Receive                                  module=consensus src="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" chId=20 msg="[CommitStep H:60 BP:PartSet{T:1 9D7FFA8570E2} BA:BA{1:X}]"
INFO[01-16|14:37:12] Receive                                  module=consensus src="Peer{MConn{188.166.68.71:46656} 0D9C8539DCCD out}" chId=20 msg="[NewRoundStep H:61 R:0 S:RoundStepNewHeight LCR:0]"
```

after several restarts, the chain is finally catching up (with WARN signals, but that's because it has to sync I guess), but looks unstable. Deploying contracts is going OK, but later on, the chain stops and I get the same message as Andy and somak12 are getting. At that point I just can't manage the chain getting up again for the root machine.

The validators seem Ok though. This is my setup:

```
#!/usr/bin/env bash
echo "Running HerenBouwChain environment setup..."
chainName=herenbouwchain

for i in `seq 0 3`
do
  eris chains rm -xf $chainName --machine "do-val$i"
  eris chains start --init-dir "${chainName}"/"${chainName}_validator_00$i" --machine "do-val$i" $chainName
  echo "Wait for do-val$i to start $chainName.."
done

eris chains rm -xf $chainName --machine do-prod0
eris chains start --init-dir "${chainName}"/"${chainName}_root_000" --machine do-prod0 $chainName
echo "Wait for do-prod0 to start $chainName.."
```

---

@marc4gov commented on [Sun Jan 22 2017](https://github.com/eris-ltd/eris-cli/issues/1138#issuecomment-274106633)

Bummer: I managed to get the chain going on do-prod0, but now it chokes on deploying contracts.
Log output: 

```
INFO[01-20|15:52:55] Receive                                  module=consensus src="Peer{MConn{188.166.67.157:46656} 4EDF0E802BF1 out}" chId=22 msg="[Vote VI:3 V:Vote{121/00/1(Prevote) 5C0CBA203EEA#PartSet{T:1 AAC9ED6FC64B} /97044898A9F8.../} VI:3]"
INFO[01-20|15:52:55] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{188.166.67.157:46656} 4EDF0E802BF1 out}" peerRound=0 height=121 round=0 prevotes=BA{4:XX_X} index=3
INFO[01-20|15:52:55] Added to prevote                         module=consensus vote="Vote{121/00/1(Prevote) 5C0CBA203EEA#PartSet{T:1 AAC9ED6FC64B} /97044898A9F8.../}" prevotes="VoteSet{H:121 R:0 T:1 +2/3:true BA{4:XX_X}}"
INFO[01-20|15:52:55] enterPrecommit(121/0). Current: 121/0/RoundStepPrevote module=consensus
NOTE[01-20|15:52:55] enterPrecommit: +2/3 prevoted proposal block. Locking module=consensus hash=5C0CBA203EEA74D42047BD14081FC1F8CFC9570B
panic: Paniced on a Consensus Failure: enterPrecommit: +2/3 prevoted for an invalid block: Wrong Block.Header.AppHash.  Expected B9E9A513B59FC0FF44D3E3C35F489EA55C460661, got 6425B68E61D99AA5E483219DAA1EE837F250400C

goroutine 33 [running]:
panic(0x55603e88dcc0, 0xc421cd8090)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-common.PanicConsensus(0x55603e88dcc0, 0xc421cd8070)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-common/errors.go:39 +0xe2
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterPrecommit(0xc42011c480, 0x79, 0x0)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:1070 +0x14f7
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc42011c480, 0x3, 0xc421cc17a0, 0xc420185080, 0x40, 0xc422347a00, 0x0, 0x0, 0xc422347a80, 0x55603dcffc47, ...)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:1440 +0x113a
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc42011c480, 0x3, 0xc421cc17a0, 0xc420185080, 0x40, 0x0, 0x0)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:1358 +0x76
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc42011c480, 0x55603e8b9620, 0xc421ccc8b0, 0xc420185080, 0x40, 0x79, 0x0, 0x4, 0xed0142956, 0x394e61d0, ...)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:668 +0x66d
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc42011c480, 0x0)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:614 +0x2c9
created by github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).startRoutines
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:320 +0x6d
```

When deploying, logs freeze for a while on do-prod0 (1 minute or so). Then, I manage to get thru, but I'm worrying about a recurring line in the logs...but maybe this is normal?

```
INFO[01-20|16:00:01] HTTPRestRPC                              module=rpcserver method=/status args=[] returns="[<types.ErisDBResult Value> <error Value>]"
INFO[01-20|16:00:01] Served RPC HTTP response                 module=rpcserver method=GET url=/status status=200 duration=1 remoteAddr=94.208.78.41:55632
```

Instead of 6 minutes, the job now takes 14 minutes to run ... 

```
....
Executing Job                                 addTaskOrder91
Return Value                                  00238EE9E9DDA88FA260E97A1476F93099D38204
Executing Job                                 addTaskOrder92
Return Value                                  225A803DE8E0E3F617E1ED3A9D88CA02E04515B1
Executing Job                                 addOrderInvoice22
Return Value                                  1
Executing Job                                 addOrderInvoice23
Return Value                                  2
copy jobs_output epm6..
17:13:26
14 minutes and 5 seconds elapsed.
writing contract addresses to jobs_output.json..
```

So, chain finally running, then trying to transact brings the chain down on do-prod0. I can't manage to get the chain restarted, logs show this:

```
INFO[01-22|08:09:00] Server started.                          module=eris/server
WARN[01-22|08:09:00] WARNING (go-rpc): Please use fully formed listening addresses, including the tcp:// or unix:// prefix module=rpcserver
NOTE[01-22|08:09:00] Starting RPC HTTP server on tcp socket 0.0.0.0:46657 module=rpcserver
EROR[01-22|08:09:00] Error with msg                           module=consensus type=*consensus.ProposalMessage peer=456BAC68E6D9229CD8B3273ABA2BED73604664B218E71F9257C215CA39273E83 error="Error invalid proposal signature" msg="[Proposal Proposal{84644/0 PartSet{T:1 FE74CCF06D44} -1 /E0F519995EE2.../}]"
INFO[01-22|08:09:00] Dialing address                          module=p2p address=188.166.70.19:46656
NOTE[01-22|08:09:00] Peer handshake                           module=p2p peerNodeInfo="&{PubKey:PubKeyEd25519{0E547B8459E4E2ABA0FE7CCD51C6A02FEFF42D2719609FE04D5E6D88A8E62BBC} Moniker:herenbouwchain_validator_002 Network:herenbouwchain RemoteAddr: ListenAddr:172.17.0.5:46656 Version:0.6.0 Other:[wire_version=0.6.0 p2p_version=0.3.3 consensus_version=v1/0.2.1 rpc_version=0.5.1/3 rpc_addr=]}"
INFO[01-22|08:09:00] Starting Peer                            module=p2p impl="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}"
INFO[01-22|08:09:00] Starting MConnection                     module=p2p impl=MConn{188.166.70.19:46656}
NOTE[01-22|08:09:00] Added peer                               module=p2p peer="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}"
NOTE[01-22|08:09:00] Dialed and added peer                    module=p2p address=188.166.70.19:46656 peer="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}"
NOTE[01-22|08:09:00] Connected to seed                        module=p2p peer="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}"
INFO[01-22|08:09:00] No votes to send, sleeping               module=consensus peer="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" peer="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" localPV=BA{4:____} peerPV=nil-BitArray localPC=BA{4:____} peerPC=nil-BitArray
NOTE[01-22|08:09:00] Receive                                  module=blockchain src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chID=40 msg="[bcStatusResponseMessage 84774]"
INFO[01-22|08:09:00] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=20 msg="[NewRoundStep H:84775 R:0 S:RoundStepPrevote LCR:0]"
INFO[01-22|08:09:00] HTTPRestRPC                              module=rpcserver method=/status args=[] returns="[<types.ErisDBResult Value> <error Value>]"
INFO[01-22|08:09:00] Served RPC HTTP response                 module=rpcserver method=GET url=/status status=200 duration=1 remoteAddr=94.208.78.41:58142
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=20 msg="[HasVote VI:1 V:{84775/00/2} VI:1]"
INFO[01-22|08:09:01] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" peerRound=0 height=84775 round=0 precommits=nil-BitArray index=1
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=20 msg="[HasVote VI:0 V:{84775/00/1} VI:0]"
INFO[01-22|08:09:01] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" peerRound=0 height=84775 round=0 prevotes=nil-BitArray index=0
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=20 msg="[NewRoundStep H:84775 R:0 S:RoundStepPrecommit LCR:0]"
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=20 msg="[HasVote VI:0 V:{84775/00/2} VI:0]"
INFO[01-22|08:09:01] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" peerRound=0 height=84775 round=0 precommits=nil-BitArray index=0
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=22 msg="[Vote VI:3 V:Vote{84644/00/2(Precommit) 433D2AEB8F91#PartSet{T:1 FE74CCF06D44} /56F4C254359C.../} VI:3]"
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=22 msg="[Vote VI:2 V:Vote{84644/00/2(Precommit) 433D2AEB8F91#PartSet{T:1 FE74CCF06D44} /80FA21F75BE9.../} VI:2]"
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=22 msg="[Vote VI:0 V:Vote{84644/00/2(Precommit) 433D2AEB8F91#PartSet{T:1 FE74CCF06D44} /6758900178A5.../} VI:0]"
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=22 msg="[Vote VI:1 V:Vote{84644/00/2(Precommit) 433D2AEB8F91#PartSet{T:1 FE74CCF06D44} /E3E0E4916522.../} VI:1]"
INFO[01-22|08:09:01] Added to precommit                       module=consensus vote="Vote{84644/00/2(Precommit) 433D2AEB8F91#PartSet{T:1 FE74CCF06D44} /56F4C254359C.../}" precommits="VoteSet{H:84644 R:0 T:2 +2/3:false BA{4:___X}}"
INFO[01-22|08:09:01] Added to precommit                       module=consensus vote="Vote{84644/00/2(Precommit) 433D2AEB8F91#PartSet{T:1 FE74CCF06D44} /80FA21F75BE9.../}" precommits="VoteSet{H:84644 R:0 T:2 +2/3:false BA{4:__XX}}"
INFO[01-22|08:09:01] Added to precommit                       module=consensus vote="Vote{84644/00/2(Precommit) 433D2AEB8F91#PartSet{T:1 FE74CCF06D44} /6758900178A5.../}" precommits="VoteSet{H:84644 R:0 T:2 +2/3:true BA{4:X_XX}}"
INFO[01-22|08:09:01] enterPrecommit(84644/0). Current: 84644/0/RoundStepPropose module=consensus
INFO[01-22|08:09:01] enterPrecommit: No +2/3 prevotes during enterPrecommit. Precommitting nil. module=consensus
INFO[01-22|08:09:01] enterCommit(84644/0). Current: 84644/0/RoundStepPrecommit module=consensus
WARN[01-22|08:09:01] Attempt to finalize failed. We don't have the commit block. module=consensus
INFO[01-22|08:09:01] Added to precommit                       module=consensus vote="Vote{84644/00/2(Precommit) 433D2AEB8F91#PartSet{T:1 FE74CCF06D44} /E3E0E4916522.../}" precommits="VoteSet{H:84644 R:0 T:2 +2/3:true BA{4:XXXX}}"
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=20 msg="[CommitStep H:84775 BP:PartSet{T:1 A07AD423E72D} BA:BA{1:X}]"
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=20 msg="[HasVote VI:3 V:{84775/00/2} VI:3]"
INFO[01-22|08:09:01] SetHasVote(round-match)                  module=consensus peer="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" peerRound=0 height=84775 round=0 precommits=nil-BitArray index=3
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=20 msg="[NewRoundStep H:84775 R:0 S:RoundStepCommit LCR:0]"
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=20 msg="[NewRoundStep H:84776 R:0 S:RoundStepNewHeight LCR:0]"
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=21 msg="[BlockPart H:84644 R:0 P:Part{#0\n  Bytes: 0101010E6865...\n  Proof: SimpleProof{\n    Aunts: []\n  }\n}]"
INFO[01-22|08:09:01] Receive                                  module=consensus src="Peer{MConn{188.166.70.19:46656} 0E547B8459E4 out}" chId=20 msg="[HasVote VI:2 V:{84775/00/2} VI:2]"
INFO[01-22|08:09:01] Received complete proposal block         module=consensus height=84644 hash=433D2AEB8F91800AB9A4412D63689D43B1909947
panic: Paniced on a Consensus Failure: +2/3 committed an invalid block: Wrong Block.Header.AppHash.  Expected 2907BF92AFA2B52F558221D8A17032ABACBA641C, got 07B8DA42AAA8334C0D1EB1724ACF94A8960A7494

goroutine 33 [running]:
panic(0x5573c8a99cc0, 0xc421809ff0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-common.PanicConsensus(0x5573c8a99cc0, 0xc421809fd0)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-common/errors.go:39 +0xe2
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc42011c780, 0x14aa4)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:1203 +0xe69
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc42011c780, 0x14aa4)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:1180 +0x136
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addProposalBlockPart(0xc42011c780, 0x14aa4, 0xc420210000, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:1349 +0x43f
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc42011c780, 0x5573c8ac5380, 0xc421800300, 0xc4201ffd40, 0x40, 0x14aa4, 0x0, 0x8, 0xed0165f9a, 0x20dfaa83, ...)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:661 +0x5ab
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc42011c780, 0x0)
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:614 +0x2c9
created by github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).startRoutines
	/go/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:320 +0x6d
```

**Comment by ramilexe** [comment]
I was looking for this error in tendermint repo and found it https://github.com/tendermint/tendermint/issues/173#issuecomment-167874768
It is fixed more than year ago

**Comment by zramsay** [comment]
closing given comment by @ramilexe and inactivity
