### ISSUE TITLE
Ran chains new, got this.

### ISSUE THREAD

**Issue by AFDudley** [eris-ltd/eris-db#97]
$ eris chains logs TEST-2016-04-13T20-25-21-57
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x8ae

goroutine 29 [sleep]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/eris-ltd/eris-db/erisdb.reap(0xc8201ad4a0)
	/go/src/github.com/eris-ltd/eris-db/erisdb/event_cache.go:70 +0x4e
created by github.com/eris-ltd/eris-db/erisdb.NewEventSubscriptions
	/go/src/github.com/eris-ltd/eris-db/erisdb/event_cache.go:62 +0x101

goroutine 30 [chan receive]:
github.com/eris-ltd/eris-db/erisdb.startNode(0xc820126e60, 0xc8200e1800, 0xc820267a40)
	/go/src/github.com/eris-ltd/eris-db/erisdb/serve.go:128 +0x19e
created by github.com/eris-ltd/eris-db/erisdb.ServeErisDB
	/go/src/github.com/eris-ltd/eris-db/erisdb/serve.go:102 +0xbaa

goroutine 31 [IO wait]:
net.runtime_pollWait(0x7f472342eb18, 0x72, 0xc8200121b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820196840, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820196840, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201967e0, 0x0, 0x7f472342eed8, 0xc8200d5020)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820028238, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820028238, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p.(*DefaultListener).listenRoutine(0xc820267c20)
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p/listener.go:115 +0x42
created by github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p.(*DefaultListener).OnStart
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p/listener.go:103 +0x55

goroutine 32 [select]:
github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p.(*AddrBook).saveRoutine(0xc8200c2270)
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p/addrbook.go:373 +0x384
created by github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p.(*AddrBook).OnStart
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p/addrbook.go:128 +0x105

goroutine 40 [IO wait]:
net.runtime_pollWait(0x7f472342e998, 0x72, 0xc8200121b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82017c610, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82017c610, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82017c5b0, 0x0, 0x7f472342eed8, 0xc820154a20)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820028458, 0x4529b0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820028458, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc8200e0660, 0x7f472342db98, 0xc820028458, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3
github.com/eris-ltd/eris-db/Godeps/_workspace/src/gopkg.in/tylerb/graceful%2ev1.(*Server).Serve(0xc82017c4d0, 0x7f472342db98, 0xc820028458, 0x0, 0x0)
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/gopkg.in/tylerb/graceful.v1/graceful.go:226 +0x3d0
github.com/eris-ltd/eris-db/server.(*ServeProcess).Start.func1(0xc820196770, 0x7f472342db98, 0xc820028458)
	/go/src/github.com/eris-ltd/eris-db/server/server.go:114 +0x46
created by github.com/eris-ltd/eris-db/server.(*ServeProcess).Start
	/go/src/github.com/eris-ltd/eris-db/server/server.go:118 +0xad8

goroutine 34 [select]:
github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/consensus.(*ConsensusReactor).broadcastNewRoundStepRoutine(0xc820196690)
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/consensus/reactor.go:287 +0x191
created by github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/consensus.(*ConsensusReactor).OnStart
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/consensus/reactor.go:58 +0x27d

goroutine 35 [sleep]:
time.Sleep(0x44d7e6c0)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p.(*PEXReactor).ensurePeersRoutine(0xc820196460)
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p/pex_reactor.go:128 +0x41
created by github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p.(*PEXReactor).OnStart
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p/pex_reactor.go:46 +0xa7

goroutine 36 [chan receive]:
github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p.(*Switch).listenerRoutine(0xc8200c28f0, 0x7f472342ee68, 0xc820267c20)
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p/switch.go:350 +0x72
created by github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p.(*Switch).OnStart
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/p2p/switch.go:171 +0x298

goroutine 38 [IO wait]:
net.runtime_pollWait(0x7f472342ea58, 0x72, 0xc8200121b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82017c290, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82017c290, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82017c230, 0x0, 0x7f472342eed8, 0xc8201aa220)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820028268, 0x4529b0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820028268, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc8200e0600, 0x7f472342db98, 0xc820028268, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.Serve(0x7f472342db98, 0xc820028268, 0x7f4723425c28, 0xc8200d5fe0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1765 +0x85
github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/rpc/server.StartHTTPServer.func1(0x7f472342db98, 0xc820028268, 0x7f472342f400, 0xc8201a4a50)
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/rpc/server/http_server.go:26 +0x79
created by github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/rpc/server.StartHTTPServer
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/rpc/server/http_server.go:31 +0x36c

goroutine 44 [select]:
github.com/eris-ltd/eris-db/Godeps/_workspace/src/gopkg.in/tylerb/graceful%2ev1.(*Server).manageConnections(0xc82017c4d0, 0xc820016900, 0xc8200169c0, 0xc820016a20, 0xc820016a80)
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/gopkg.in/tylerb/graceful.v1/graceful.go:264 +0x3d9
created by github.com/eris-ltd/eris-db/Godeps/_workspace/src/gopkg.in/tylerb/graceful%2ev1.(*Server).Serve
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/gopkg.in/tylerb/graceful.v1/graceful.go:215 +0x1a8

goroutine 41 [chan receive]:
github.com/eris-ltd/eris-db/server.(*ServeProcess).Start.func2(0xc820196770)
	/go/src/github.com/eris-ltd/eris-db/server/server.go:123 +0x3e
created by github.com/eris-ltd/eris-db/server.(*ServeProcess).Start
	/go/src/github.com/eris-ltd/eris-db/server/server.go:126 +0xafd

goroutine 42 [chan receive]:
github.com/eris-ltd/eris-db/server.(*ServeProcess).Start.func3(0xc820196770)
	/go/src/github.com/eris-ltd/eris-db/server/server.go:130 +0x4c
created by github.com/eris-ltd/eris-db/server.(*ServeProcess).Start
	/go/src/github.com/eris-ltd/eris-db/server/server.go:135 +0xb22

goroutine 43 [sleep]:
time.Sleep(0xb2d05e00)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/consensus.(*ConsensusState).EnterPropose.func2(0xc8200a43c0, 0x1, 0x0)
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/consensus/state.go:580 +0x23
created by github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/consensus.(*ConsensusState).EnterPropose
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/github.com/tendermint/tendermint/consensus/state.go:582 +0x7a5

goroutine 45 [select, locked to thread]:
runtime.gopark(0xcc3650, 0xc820686f28, 0xb84028, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820686f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820686f28)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 46 [chan receive]:
github.com/eris-ltd/eris-db/Godeps/_workspace/src/gopkg.in/tylerb/graceful%2ev1.(*Server).handleInterrupt(0xc82017c4d0, 0xc820016ae0, 0x7f472342db98, 0xc820028458)
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/gopkg.in/tylerb/graceful.v1/graceful.go:298 +0x3a
created by github.com/eris-ltd/eris-db/Godeps/_workspace/src/gopkg.in/tylerb/graceful%2ev1.(*Server).Serve
	/go/src/github.com/eris-ltd/eris-db/Godeps/_workspace/src/gopkg.in/tylerb/graceful.v1/graceful.go:222 +0x3a2
ifExit
Error starting erisdb
Error starting erisdb

**Comment by AFDudley** [comment]
got it resolved, thanks folks!

**Comment by AFDudley** [comment]
might be an error in the docs, but i'm too busy to check...
